data_dir: data

prepare:
  train_split: 0.75
  shuffle: true
  seed: 6
  data: data/data.zip

train:
  weights: src/models/segment/yolov5s-seg.pt
  cfg: src/models/segment/yolov5s-seg.yaml
  data: data/dataset.yaml
  hyp: src/data/hyps/hyp.scratch-low.yaml
  epochs: 2
  batch_size: 16
  imgsz: 640
  rect: false
  resume: True
  nosave: false
  noval: false
  noautoanchor: false
  noplots: false
  evolve:
  bucket: ''
  cache: ram
  image_weights: false
  device: cpu
  multi_scale: false
  single_cls: false
  optimizer: SGD # SGD, Adam, AdamW
  sync_bn: false
  workers: 4
  project: model
  name: ''
  exist_ok: false
  quad: false
  cos_lr: false
  label_smoothing: 0.0
  patience: 100
  freeze:     # backbone=10, first3=0 1 2
  - 0
  save_period: -1
  seed: 0
  local_rank: -1
  # upload_dataset: false
  # entity:
  # bbox_interval: -1
  artifact_alias: latest
   # Segmentation
  no_overlap: false
  # overlap_mask: True  # (bool) masks should overlap during training (segment train only)
  mask_ratio: 4  # (int) mask downsample ratio (segment train only)
  

export:
  weights: model/weights/best.pt
  include:
  - onnx
